-- --------------------------------------------------------
-- Hôte:                         127.0.0.1
-- Version du serveur:           8.0.31 - MySQL Community Server - GPL
-- SE du serveur:                Win64
-- HeidiSQL Version:             12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Listage de la structure de la table projet_groupe_envol_sarl. ge_pays_destinations
CREATE TABLE IF NOT EXISTS `ge_pays_destinations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nom_pays` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `icon_image_pays` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_couverture1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_couverture2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `breve_description` text COLLATE utf8mb4_unicode_ci,
  `benefice` text COLLATE utf8mb4_unicode_ci,
  `whychoose` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table projet_groupe_envol_sarl.ge_pays_destinations : ~4 rows (environ)
INSERT INTO `ge_pays_destinations` (`id`, `nom_pays`, `icon_image_pays`, `image_couverture1`, `image_couverture2`, `image1`, `image2`, `description`, `breve_description`, `benefice`, `whychoose`, `created_at`, `updated_at`) VALUES
	(1, 'Etats-Unis', 'usa.jpg', '01.jpg', 'single-2.jpg', '01.jpg', '02.jpg', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', '2024-09-12 13:48:10', '2024-09-12 13:48:10'),
	(2, 'France', 'france.jpg', 'single-3.jpg', 'single-2.jpg', 'single-3.jpg', 'single-4.jpg', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', '2024-09-12 13:48:10', '2024-09-12 13:48:10'),
	(3, 'Canada', 'canada.jpg', 'single-4.jpg', 'single-2.jpg', 'single-4.jpg', 'single-3.jpg', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', '2024-09-12 13:48:10', '2024-09-12 13:48:10'),
	(4, 'Royaume Uni', 'uk.jpg', 'single-3.jpg', 'single-2.jpg', 'single-3.jpg', 'single-2.jpg', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et. But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', 'Power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection.', '2024-09-12 13:48:10', '2024-09-12 13:48:10');

-- Listage de la structure de la table projet_groupe_envol_sarl. ge_teams
CREATE TABLE IF NOT EXISTS `ge_teams` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `titre_member` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nom_member` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `prenom_member` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `poste_member` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sexe` enum('M','F') COLLATE utf8mb4_unicode_ci NOT NULL,
  `telephone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_member` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `adresse` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bio_member` text COLLATE utf8mb4_unicode_ci,
  `facebook` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `youtube` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `twitter` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linkedin` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `photo_member` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table projet_groupe_envol_sarl.ge_teams : ~6 rows (environ)
INSERT INTO `ge_teams` (`id`, `titre_member`, `nom_member`, `prenom_member`, `poste_member`, `sexe`, `telephone`, `email_member`, `adresse`, `bio_member`, `facebook`, `youtube`, `twitter`, `linkedin`, `photo_member`, `created_at`, `updated_at`) VALUES
	(1, 'M.', 'AVANON', 'Hospice', 'Directeur Général', 'M', '+2298989898', 'fopisso21@gmail.com', 'Calavi, A IBIS', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid idunt ut labore et dolore magna aliqua.enim minim veniam, quis nostrud exer citation ullamco laboris nisi aliquip com modo consequat. Duis aute irure dolor in reprenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit volup tatem acusantium dolor emque laud antium.', '#', '#', '#', '#', 'team-1.jpg', '2024-08-14 14:11:21', '2024-08-14 14:11:21'),
	(2, 'M.', 'ALODEHITO', 'Fidèle', 'Ressources Humaines', 'M', '+2298989898', 'fopisso21@gmail.com', 'Calavi, A IBIS', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid idunt ut labore et dolore magna aliqua.enim minim veniam, quis nostrud exer citation ullamco laboris nisi aliquip com modo consequat. Duis aute irure dolor in reprenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit volup tatem acusantium dolor emque laud antium.', '#', '#', '#', '#', 'team-2.jpg', '2024-08-14 14:11:22', '2024-08-14 14:11:22'),
	(3, 'Mme.', 'ALODEHITO', 'Saraï', 'Directrice Administrative et Financière', 'M', '+2298989898', 'fopisso21@gmail.com', 'Calavi, A IBIS', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid idunt ut labore et dolore magna aliqua.enim minim veniam, quis nostrud exer citation ullamco laboris nisi aliquip com modo consequat. Duis aute irure dolor in reprenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit volup tatem acusantium dolor emque laud antium.', '#', '#', '#', '#', 'team-3.jpg', '2024-08-14 14:11:22', '2024-08-14 14:11:22'),
	(4, 'M.', 'XXX', 'XXXX', 'Agent', 'M', '+2298989898', 'fopisso21@gmail.com', 'Calavi, A IBIS', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid idunt ut labore et dolore magna aliqua.enim minim veniam, quis nostrud exer citation ullamco laboris nisi aliquip com modo consequat. Duis aute irure dolor in reprenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit volup tatem acusantium dolor emque laud antium.', '#', '#', '#', '#', 'team-4.jpg', '2024-08-14 14:11:22', '2024-08-14 14:11:22'),
	(5, 'M.', 'XXX', 'XXXX', 'Agent', 'M', '+2298989898', 'fopisso21@gmail.com', 'Calavi, A IBIS', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid idunt ut labore et dolore magna aliqua.enim minim veniam, quis nostrud exer citation ullamco laboris nisi aliquip com modo consequat. Duis aute irure dolor in reprenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit volup tatem acusantium dolor emque laud antium.', '#', '#', '#', '#', 'team-5.jpg', '2024-08-14 14:11:22', '2024-08-14 14:11:22'),
	(6, 'M.', 'XXX', 'XXXX', 'Agent', 'M', '+2298989898', 'fopisso21@gmail.com', 'Calavi, A IBIS', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incid idunt ut labore et dolore magna aliqua.enim minim veniam, quis nostrud exer citation ullamco laboris nisi aliquip com modo consequat. Duis aute irure dolor in reprenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit volup tatem acusantium dolor emque laud antium.', '#', '#', '#', '#', 'team-6.jpg', '2024-08-14 14:11:22', '2024-08-14 14:11:22');

-- Listage de la structure de la table projet_groupe_envol_sarl. services
CREATE TABLE IF NOT EXISTS `services` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nom_service` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nom_court_service` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `statut_service` enum('gratuit','payant') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'payant',
  `frais_inscription` double NOT NULL DEFAULT '0',
  `devise` enum('FCFA') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'FCFA',
  `url_service` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `url_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `etat_service` tinyint DEFAULT '0',
  `image` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `courte_description` text COLLATE utf8mb4_unicode_ci,
  `route` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table projet_groupe_envol_sarl.services : ~9 rows (environ)
INSERT INTO `services` (`id`, `nom_service`, `nom_court_service`, `statut_service`, `frais_inscription`, `devise`, `url_service`, `url_name`, `etat_service`, `image`, `description`, `courte_description`, `route`, `created_at`, `updated_at`) VALUES
	(1, 'Conseils et assistance Visa-voyage', 'Visa voyage', 'payant', 1, 'FCFA', 'afficherDetailServiceConseilAssistanceVoyage', 'conseil-assistance-voyage', 0, 'assistance_voyage.jpg', 'Nous vous aidons à concrétiser vos projets de voyage.', 'Nous vous aidons à concrétiser vos projets de voyage.', NULL, '2024-07-08 12:53:49', '2024-07-08 12:53:49'),
	(2, 'Intermédiation de récrutement', 'Intermédiation', 'payant', 1, 'FCFA', 'afficherDetailServiceIntermediationRecrutement', 'intermediation-recrutement', 0, 'intermediation.jpg', 'Vous rêvez de travailler à l\'extérieur ? Nous avons des opportunités pour vous', 'Vous rêvez de travailler à l\'extérieur ? Nous avons des opportunités pour vous', NULL, '2024-07-08 12:53:49', '2024-07-08 12:53:49'),
	(3, 'Négoces', 'Négoces', 'payant', 1, 'FCFA', 'afficherDetailServiceNegoces', 'negoces', 0, 'negoces.jpg', 'Nous menons des activités de négoces pour des structures même au niveau international.', 'Nous menons des activités de négoces pour des structures même au niveau international.', NULL, '2024-07-08 12:53:49', '2024-07-08 12:53:49'),
	(4, 'Bourses d\'étude et de formation', 'Bourses d\'étude', 'payant', 1, 'FCFA', 'afficherDetailServiceBourse', 'bourses-etudes-formation', 0, 'education.jpg', 'Votre éducation est très importante pour nous. Nous cherchons des bourses d\'étude et de formation pour vous.', 'Votre éducation est très importante pour nous. Nous cherchons des bourses d\'étude et de formation pour vous.', NULL, '2024-07-08 12:53:49', '2024-07-08 12:53:49'),
	(5, 'Vente de billet d\'avion', 'Vente de billet d\'avion', 'payant', 1, 'FCFA', 'afficherDetailServiceVenteBilletAvion', 'vente-billet-avion', 0, 'billet_avion.jpg', 'Nous faisons les courses pour vous alléger votre voyage. Nous pouvons vous vendre les billets d\'avion et vous l\'apporter chez vous en toute tranquillité.', 'Nous faisons les courses pour vous alléger votre voyage. Nous pouvons vous vendre les billets d\'avion et vous l\'apporter chez vous en toute tranquillité.', NULL, '2024-07-08 12:53:49', '2024-07-08 12:53:49'),
	(6, 'Assurance de voyage', 'Assurance de voyage', 'payant', 1, 'FCFA', 'afficherDetailServiceAssuranceVoyage', 'assurance-voyage', 0, 'assurance_voyage.jpg', 'Nous sommes dans l\'assurance des voyage. Nous assurons vos arrières pour vous permettre de profiter à fond de vos voyage et d\'atteindre pleinement vos obectifs..', 'Nous sommes dans l\'assurance des voyage. Nous assurons vos arrières pour vous permettre de profiter à fond de vos voyage et d\'atteindre pleinement vos obectifs..', NULL, '2024-07-08 12:53:49', '2024-07-08 12:53:49'),
	(7, 'Visa Etudiant', 'Visa Etudiant', 'payant', 1, 'FCFA', 'afficherDetailServiceVisaEtudiant', 'visa-etudiant', 1, 'visa_etudiant.jpg', 'Vous avez besoin d\'un visa Etudiant ?', 'Vous avez besoin d\'un visa Etudiant ?', NULL, '2024-07-10 11:40:52', '2024-07-10 11:40:52'),
	(8, 'Visa Travailleur', 'Visa Travailleur', 'payant', 1, 'FCFA', 'afficherDetailServiceVisaTravailleur', 'visa-travailleur', 1, 'visa_travailleur.jpg', 'Vous avez besoin d\'un visa Travailleur ?', 'Vous avez besoin d\'un visa Travailleur ?', NULL, '2024-07-10 11:40:52', '2024-07-10 11:40:52'),
	(9, 'Visa Visiteur', 'Visa Visiteur', 'payant', 1, 'FCFA', 'afficherDetailServiceVisaVisiteur', 'visa-visiteur', 1, 'visa_visiteur.jpg', 'Vous avez besoin d\'un visa Visiteur ?', 'Vous avez besoin d\'un visa Visiteur ?', NULL, '2024-07-10 11:40:52', '2024-07-10 11:40:52');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
